[project]
name = "web-drawing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.1",
    "flask>=3.1.2",
    "ipykernel>=7.1.0",
    "numpy>=2.4.1",
    "pillow>=12.1.0",
    "scipy>=1.17.0",
]
